-- TABLE: FOURNISSEUR

DROP TABLE IF EXISTS PROD_FOURNI;

DROP TABLE IF EXISTS PARAMETRE;

DROP TABLE IF EXISTS IMG_PROD;

DROP TABLE IF EXISTS FAVORI;

DROP TABLE IF EXISTS AVIS;

DROP TABLE IF EXISTS FOURNISSEUR;

DROP TABLE IF EXISTS COMMANDE_PROD;

DROP TABLE IF EXISTS COMMANDE;

DROP TABLE IF EXISTS CLIENT;

DROP TABLE IF EXISTS PRODUIT;

DROP TABLE IF EXISTS CATEGORIE_PROD;

DROP TABLE IF EXISTS TYPE_PROD;

CREATE TABLE IF NOT EXISTS FOURNISSEUR (
    ID_FOURNISSEUR INTEGER NOT NULL AUTO_INCREMENT,
    NOM_FOURNISSEUR VARCHAR(64) NOT NULL,
    LOCALITE_FOURNISSEUR VARCHAR(128) NOT NULL,
    PRODUIT_FOURNIT VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID_FOURNISSEUR)
);

CREATE TABLE IF NOT EXISTS TYPE_PROD (
    ID_TYPEPROD INTEGER NOT NULL AUTO_INCREMENT,
    NOM_TYPE VARCHAR(32) NOT NULL CHECK (NOM_TYPE IN ('homme', 'femme')),
    PRIMARY KEY (ID_TYPEPROD)
);

-- TABLE: PRODUIT

CREATE TABLE IF NOT EXISTS CATEGORIE_PROD (
    ID_CATEGORIEPROD INTEGER NOT NULL AUTO_INCREMENT,
    NOM_CATEGORIE VARCHAR(125) NOT NULL CHECK ( NOM_CATEGORIE IN ( 'bijoux', 'pendentifs', 'bracelet', 'porte-clef', 'accessoires' ) ),
    PRIMARY KEY (ID_CATEGORIEPROD)
);

CREATE TABLE IF NOT EXISTS CLIENT (
    ID_CLIENT INTEGER NOT NULL AUTO_INCREMENT,
    NOM_CLI VARCHAR(128) NOT NULL,
    PRENOM_CLI VARCHAR(128) NOT NULL,
    EMAIL_CLI VARCHAR(128) NOT NULL UNIQUE CHECK (EMAIL_CLI LIKE '%@%.%'),
    MDP_CLI VARCHAR(300) NOT NULL,
    TEL_CLI VARCHAR(15) NOT NULL CHECK (TEL_CLI LIKE '+41__ ___ __ __'),
    STATUT_CLI VARCHAR(16) NOT NULL DEFAULT 'normal' CHECK ( STATUT_CLI IN ('normal', 'admin','inactif') ),
    PHOTO_PROFILE VARCHAR(128) NOT NULL DEFAULT "./photos/profilpic/profiledefault.jpg",
    NEWSLETTER_CLI VARCHAR(5) NOT NULL DEFAULT 'false' CHECK (NEWSLETTER_CLI IN ('true' , 'false')),
    PRIMARY KEY (ID_CLIENT)
);

-- TABLE: COMMANDE

CREATE TABLE IF NOT EXISTS COMMANDE (
    ID_COMMANDE INTEGER NOT NULL AUTO_INCREMENT,
    ID_CLIENT INTEGER NOT NULL,
    DATE_CMD DATETIME NOT NULL,
    STATUT_CMD VARCHAR(16) NOT NULL DEFAULT 'en cours' CHECK ( STATUT_CMD IN ( 'en cours', 'acheter' ) ),
    PRIMARY KEY (ID_COMMANDE),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID_CLIENT)
);

-- TABLE: CLIENT

CREATE TABLE IF NOT EXISTS PRODUIT (
    ID_PRODUIT INTEGER NOT NULL AUTO_INCREMENT,
    ID_TYPEPROD INTEGER NOT NULL,
    ID_CATEGORIEPROD INTEGER NOT NULL,
    NOM_PRODUIT VARCHAR(128) NULL,
    DESCRIPTION_PRODUIT VARCHAR(255) NULL,
    PRIX_PRODUIT FLOAT NULL,
    STOCK_PRODUIT INTEGER NULL,
    STATUT_PROD VARCHAR(16) NOT NULL DEFAULT 'disponible' CHECK ( STATUT_PROD IN ('disponible','Écartés') ),
    PRIMARY KEY (ID_PRODUIT),
    FOREIGN KEY (ID_TYPEPROD) REFERENCES TYPE_PROD (ID_TYPEPROD),
    FOREIGN KEY (ID_CATEGORIEPROD) REFERENCES CATEGORIE_PROD (ID_CATEGORIEPROD)
);

CREATE TABLE IF NOT EXISTS IMG_PROD (
    ID_IMGPROD INTEGER NOT NULL AUTO_INCREMENT,
    ID_PRODUIT INTEGER NOT NULL,
    IMAGE_PROD VARCHAR(150) NOT NULL,
    PRIMARY KEY (ID_IMGPROD),
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT (ID_PRODUIT)
);

-- TABLE: PARAMETRE

CREATE TABLE IF NOT EXISTS PARAMETRE (
    DESCRIPTION_WEBSITE LONGTEXT NOT NULL,
    ADRESSE_ENTREPRISE VARCHAR(128) NOT NULL,
    TEL_ENTREPRISE VARCHAR(128) NOT NULL CHECK ( TEL_ENTREPRISE LIKE '+41__ ___ __ __' ),
    MAIL_ENTREPRISE VARCHAR(128) NOT NULL,
    CODE_REDUCTION VARCHAR(128) NULL
);

-- TABLE: PROD_FOURNI

CREATE TABLE IF NOT EXISTS PROD_FOURNI (
    ID_PRODUIT INTEGER NOT NULL,
    ID_FOURNISSEUR INTEGER NOT NULL,
    PRIMARY KEY (ID_PRODUIT, ID_FOURNISSEUR),
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT (ID_PRODUIT),
    FOREIGN KEY (ID_FOURNISSEUR) REFERENCES FOURNISSEUR (ID_FOURNISSEUR)
);

-- TABLE: FAVORI

CREATE TABLE IF NOT EXISTS FAVORI (
    ID_CLIENT INTEGER NOT NULL,
    ID_PRODUIT INTEGER NOT NULL,
    PRIMARY KEY (ID_CLIENT, ID_PRODUIT),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID_CLIENT),
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT (ID_PRODUIT)
);

-- TABLE: COMMANDE_PROD

CREATE TABLE IF NOT EXISTS COMMANDE_PROD (
    ID_PRODUIT INTEGER NOT NULL,
    ID_COMMANDE INTEGER NOT NULL,
    QUANTITE_CMD INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_PRODUIT, ID_COMMANDE),
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT (ID_PRODUIT),
    FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDE (ID_COMMANDE)
);

-- TABLE: AVIS

CREATE TABLE IF NOT EXISTS AVIS (
    ID_AVIS INTEGER NOT NULL AUTO_INCREMENT,
    ID_CLIENT INTEGER NOT NULL,
    ID_PRODUIT INTEGER NOT NULL,
    NOTE_AVIS INTEGER NOT NULL,
    DESCRIPTION_AVIS VARCHAR(255) NULL,
    DATE_AVIS DATETIME NOT NULL,
    TYPE_AVIS VARCHAR(7) NOT NULL DEFAULT 'public' CHECK ( TYPE_AVIS IN ('public', 'priver') ),
    PRIMARY KEY (ID_AVIS),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID_CLIENT),
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT (ID_PRODUIT)
);

/*---------------------insertion type-------------------------*/

INSERT INTO TYPE_PROD (
    NOM_TYPE
) VALUES(
    'homme'
);

INSERT INTO TYPE_PROD (
    NOM_TYPE
) VALUES(
    'femme'
);

/*---------------------insertion categorie-------------------------*/

INSERT INTO CATEGORIE_PROD(
    NOM_CATEGORIE
) VALUES (
    'bijoux'
);

INSERT INTO CATEGORIE_PROD(
    NOM_CATEGORIE
) VALUES (
    'pendentifs'
);

INSERT INTO CATEGORIE_PROD(
    NOM_CATEGORIE
) VALUES (
    'bracelet'
);

INSERT INTO CATEGORIE_PROD(
    NOM_CATEGORIE
) VALUES (
    'porte-clef'
);

INSERT INTO CATEGORIE_PROD(
    NOM_CATEGORIE
) VALUES (
    'accessoires'
);

insert into PARAMETRE(
    DESCRIPTION_WEBSITE,
    ADRESSE_ENTREPRISE,
    TEL_ENTREPRISE,
    MAIL_ENTREPRISE,
    CODE_REDUCTION
) VALUES (
    'Nina, une jeune femme rêveuse, une amoureuse de la vie dont l’âme s’enrichie au fil de ses rencontres et de ses découvertes. 
    Passionnée par le dessin, elle passe son enfance à imaginer et reproduire sur son carnet les objets et les situations qui défilent dans sa tête. <br> <br> <br> <br>
    Aujourd’hui, elle s’est créée un univers bien à elle, inspiré des rêves de son passé, des pays qu’elle a visité et de sa culture brasil-suisse. 
    Curieuse et admirative, elle rapporte de ses voyages des inspirations, des souvenirs et autres trésors. <br> <br> <br> <br>
    Afin de satisfaire sa soif de création, elle lance en 1998 sa première ligne de bijoux dans un esprit bohème chic.',
    'plan-les-ouates',
    '+4179 111 11 11',
    'ninaceration@gmail.com',
    'leptun'
);

